version: '3.8'
services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - "app"
    ports:
      - "80:80"

  app:
    container_name: app
    build:
      args:
        user: zhenya
        uid: 1000
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
